export const lightTheme = {
  background: '#ffffff',
  color: '#333333',
  accentColor: '#0066cc',
  secondaryAccent: '#666666',
  chronoTheme: {
    cardBgColor: 'white',
    cardForeColor: '#333333',
    titleColor: 'white',
  },
  timelineLineColor: '#e0e0e0',
  cardBackground: '#ffffff',
  cardFooterBackground: '#f8f9fa',
  cardBorderColor: '#e0e0e0',
  navbarTheme: {
    linkColor: '#666666',
    linkHoverColor: '#333333',
    linkActiveColor: '#0066cc',
  },
  bsPrimaryVariant: 'light',
  bsSecondaryVariant: 'dark',
  socialIconBgColor: '#0066cc',
  textSecondary: '#666666',
  borderColor: '#e0e0e0',
  shadowColor: 'rgba(0, 0, 0, 0.05)',
};

export const darkTheme = {
  background: '#1a1a1a',
  color: '#ffffff',
  accentColor: '#4a9eff',
  secondaryAccent: '#e0e0e0',
  chronoTheme: {
    cardBgColor: '#2a2a2a',
    cardForeColor: '#ffffff',
    titleColor: 'black',
  },
  timelineLineColor: '#404040',
  cardBackground: '#2a2a2a',
  cardFooterBackground: '#333333',
  cardBorderColor: '#404040',
  navbarTheme: {
    linkColor: '#e0e0e0',
    linkHoverColor: '#ffffff',
    linkActiveColor: '#4a9eff',
  },
  bsPrimaryVariant: 'dark',
  bsSecondaryVariant: 'light',
  socialIconBgColor: '#4a9eff',
  textSecondary: '#e0e0e0',
  borderColor: '#404040',
  shadowColor: 'rgba(0, 0, 0, 0.2)',
};
